% Define the polygon vertices

pv = [0 0;  1 0; 1 -0.5;
                        2 -0.5;
                        2 0;
                        3 0;
                        3 1;
                        0 1; 0 0];

##pv = [-1 -1;
##                    -0.55, -1;
##                    -0.55, 0;
##                    -0.45, 0;
##                    -0.45, -1;
##                    0.45, -1;
##                    0.45, 0;
##                    0.55, 0;
##                    0.55, -1;
##                    1, -1;
##                    1, 1;
##                    -1, 1;
##                    -1, -1];
##
##

% Generate sample points in the bounding box of the polygon
x = linspace(min(pv(:, 1)), max(pv(:, 1)), 100);
y = linspace(min(pv(:, 2)), max(pv(:, 2)), 100);
[X, Y] = meshgrid(x, y);
sample_points = [X(:), Y(:)];

% Calculate distance values using dpoly
d = dpoly(sample_points, pv);

% Plot the results
scatter(sample_points(:, 1), sample_points(:, 2), 10, d, 'filled');
colorbar;
hold on;
plot(pv(:, 1), pv(:, 2), 'r', 'LineWidth', 2);
axis equal;
title('Distance Field Generated by dpoly');
xlabel('X');
ylabel('Y');

